import header2 from "../images/header2.png"
import header3 from "../images/header3.png"
import card1Head from "../images/card1Head.png"
import logo4 from "../images/logo4.png"
import logo1 from "../images/logo1.png"
import logo2 from "../images/logo2.png"
import logo3 from "../images/logo3.png"
import logo5 from "../images/logo5.png"
import logo6 from "../images/logo6.png"

export const cardData = [
  {
    id: 'testID1',
    headerImage: header2,
    logo: logo4,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID2',
    headerImage: header3,
    logo: logo1,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID3',
    headerImage: card1Head,
    logo: logo2,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum.',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID4',
    headerImage: card1Head,
    logo: logo3,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID5',
    headerImage: header2,
    logo: logo5,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID6',
    headerImage: header2,
    logo: logo6,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID7',
    headerImage: card1Head,
    logo: logo1,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID8',
    headerImage: header2,
    logo: logo2,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID9',
    headerImage: card1Head,
    logo: logo3,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID10',
    headerImage: header2,
    logo: logo6,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID11',
    headerImage: card1Head,
    logo: logo3,
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
];
